# Generated by Django 4.0.2 on 2022-03-22 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productName', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('calories', models.IntegerField()),
                ('productID', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('firstName', models.CharField(max_length=100, null=True)),
                ('lastName', models.CharField(max_length=100, null=True)),
                ('email', models.CharField(max_length=100, null=True)),
                ('password', models.CharField(max_length=20, null=True)),
                ('userId', models.IntegerField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='OrderDetail',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('status', models.CharField(max_length=20, null=True)),
                ('order_timestamp', models.DateTimeField(null=True)),
                ('amount', models.IntegerField()),
                ('address', models.TextField(null=True)),
                ('firstName', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='burgerwebsite.user')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='burgerwebsite.product')),
            ],
        ),
    ]
