# Generated by Django 4.0.2 on 2022-03-22 05:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgerwebsite', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('orderId', models.IntegerField(primary_key=True, serialize=False)),
                ('orderTotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(max_length=20, null=True)),
                ('email', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to='burgerwebsite.user')),
                ('productID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderdetails', to='burgerwebsite.orderdetail')),
            ],
        ),
    ]
