# Generated by Django 4.0.2 on 2022-03-22 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('burgerwebsite', '0002_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100, null=True)),
                ('orderId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orderid', to='burgerwebsite.order')),
                ('orderTotal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='burgerwebsite.order')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='userid', to='burgerwebsite.user')),
            ],
        ),
    ]
